[project]
name = "pdfnumbering"
requires-python = ">=3.10"
dependencies = [
    "fpdf2",
    "pypdf",
]
dynamic = ["version"]

[project.scripts]
pdfnumbering = "pdfnumbering.cli:main"

[tool.setuptools.dynamic]
version = { attr = "pdfnumbering.__version__" }
